### ISSUE TITLE
Master branch example not working

### ISSUE THREAD

**Issue by Fabien-Chouteau** [JeremyGrosser/rp#1]
Hello @JeremyGrosser,

I just tried the master example on my Pico and I see no blinking, did you forget to push something to the repo?

**Comment by JeremyGrosser** [comment]
I haven't implemented delay yet, systick or otherwise, so it is blinking, but you can only tell with a debugger or oscilloscope as it's in the khz range.

I just got PLL config working on the hal branch, so timers aren't far behind.

**Comment by JeremyGrosser** [comment]
Oh, and I've got it setup for an LED on GP15, not the onboard one, which I only recently learned exists

**Comment by Fabien-Chouteau** [comment]
Ok I see ^^

**Comment by JeremyGrosser** [comment]
master branch example should blink properly now.
